export const formFields = {
    '5-Day Club': {
      fields: ['date', 'time', 'phone', 'address', 'city', 'state', 'zip', 'missionary', 'comments', 'helper', 'offering'],
      initialValues: {
        date: '',
        time: '',
        phone: '',
        address: '',
        city: '',
        state: '',
        zip: '',
        missionary: '',
        comments: '',
        helper: '',
        offering: '00.00',
        eventType: 'fivedayclub',
      },
      validations: {
        date: [(value) => value.length > 0, 'Date is required'],
        time: [(value) => value.length > 0, 'Time is required'],
        phone: [(value) => value.length > 0, 'Phone number is required'],
        address: [(value) => value.length > 0, 'Address is required'],
        city: [(value) => value.length > 0, 'City is required'],
        state: [(value) => value.length > 0, 'State is required'],
        zip: [(value) => value.length > 0, 'Zip code is required'],
        missionary: [(value) => value.length > 0, 'Missionary is required'],
        helper: [(value) => value.length > 0, 'Helper is required'],
        offering: [(value) => value.length > 0, 'Offering is required'],
      },
    },
    'Good News Camp': {
      fields: ['date', 'time', 'phone', 'address', 'city', 'state', 'zip', 'county', 'missionary', 'comments', 'offering'],
      initialValues: {
        date: '',
        time: '',
        phone: '',
        address: '',
        city: '',
        state: '',
        zip: '',
        county: '',
        missionary: '',
        comments: '',
        offering: '00.00',
        eventType: 'goodnewsdaycamp',
      },
      validations: {
        date: [(value) => value.length > 0, 'Date is required'],
        time: [(value) => value.length > 0, 'Time is required'],
        phone: [(value) => value.length > 0, 'Phone number is required'],
        address: [(value) => value.length > 0, 'Address is required'],
        city: [(value) => value.length > 0, 'City is required'],
        state: [(value) => value.length > 0, 'State is required'],
        zip: [(value) => value.length > 0, 'Zip code is required'],
        county: [(value) => value.length > 0, 'County is required'],
        missionary: [(value) => value.length > 0, 'Missionary is required'],
        offering: [(value) => value.length > 0, 'Offering is required'],
      },
    },
    'Teacher Training Classes': {
      fields: ['date', 'time', 'county', 'location'],
      initialValues: {
        date: '',
        time: '',
        county: '',
        location: '',
        eventType: 'teachertrainingclass',
      },
      validations: {
        date: [(value) => value.length > 0, 'Date is required'],
        time: [(value) => value.length > 0, 'Time is required'],
        county: [(value) => value.length > 0, 'County is required'],
        location: [(value) => value.length > 0, 'Location is required'],
      },
    },
    'Good News Club': {
      fields: ['date', 'time', 'phone', 'address', 'city', 'state', 'zip', 'missionary', 'comments', 'hostess', 'offering'],
      initialValues: {
        date: '',
        time: '',
        phone: '',
        address: '',
        city: '',
        state: '',
        zip: '',
        missionary: '',
        comments: '',
        hostess: '',
        offering: '00.00',
        eventType: 'goodnewsclub',
      },
      validations: {
        date: [(value) => value.length > 0, 'Date is required'],
        time: [(value) => value.length > 0, 'Time is required'],
        phone: [(value) => value.length > 0, 'Phone number is required'],
        address: [(value) => value.length > 0, 'Address is required'],
        city: [(value) => value.length > 0, 'City is required'],
        state: [(value) => value.length > 0, 'State is required'],
        zip: [(value) => value.length > 0, 'Zip code is required'],
        missionary: [(value) => value.length > 0, 'Missionary is required'],
        hostess: [(value) => value.length > 0, 'Hostess is required'],
        offering: [(value) => value.length > 0, 'Offering is required'],
      },
    },
    'Released Times': {
      fields: ['date', 'time', 'phone', 'address', 'city', 'state', 'zip', 'missionary', 'comments', 'hostess', 'offering'],
      initialValues: {
        date: '',
        time: '',
        phone: '',
        address: '',
        city: '',
        state: '',
        zip: '',
        missionary: '',
        comments: '',
        hostess: '',
        offering: '00.00',
        eventType: 'releasedtimes',
      },
      validations: {
        date: [(value) => value.length > 0, 'Date is required'],
        time: [(value) => value.length > 0, 'Time is required'],
        phone: [(value) => value.length > 0, 'Phone number is required'],
        address: [(value) => value.length > 0, 'Address is required'],
        city: [(value) => value.length > 0, 'City is required'],
        state: [(value) => value.length > 0, 'State is required'],
        zip: [(value) => value.length > 0, 'Zip code is required'],
        missionary: [(value) => value.length > 0, 'Missionary is required'],
        hostess: [(value) => value.length > 0, 'Hostess is required'],
        offering: [(value) => value.length > 0, 'Offering is required'],
      },
    },
  };
  