name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # O la rama en la que deseas hacer el deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Cambia a la versión que uses en tu proyecto

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Asegúrate de tener este script en tu package.json

      - name: Firebase Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Usa el secreto aquí
        run: npx firebase-tools deploy --only hosting
